config/routes.rb
Rails.application.routes.draw do

  root "rants#index"
  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
    get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get '/signout' => 'authentication#destroy', as: :signout
  get '/search' => 'rants#index', as: :search

  resources :users
  resources :rants

end

app/models/rant.rb
class Rant < ActiveRecord::Base

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { minimum: 144 }

  def self.search(search)
    where("body ILIKE ? or title ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base


  def full_name
    "#{first_name} #{last_name}"
  end

  has_many :rants

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email, case_sensitive: false
  has_secure_password

  include Gravtastic
  gravtastic

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Gravtastic
  gravtastic

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to rants_path
    else
      @sign_in_error = "Username / password combination is invalid"
      redirect_to rants_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :owner_check, only: [:edit, :update, :destroy]

  def index
    @rants = Rant.search(params[:search])
    @user = User.all
  end

  def new
    if current_user
      @rant = Rant.new
    else
      redirect_to rants_path, notice: 'You must log in!'
    end
  end

  def show
    @rant = Rant.find(params[:id])
  end

  def create
    @rant = Rant.new(params.require(:rant).permit(:title, :body))
    @rant.user_id = current_user.id
    if @rant.save
      redirect_to rants_path, notice: 'Rant was successfully created.'
    else
      render :new, notice: "You've gotta say more than that!"
    end
  end

  def edit
      @rant = Rant.find(params[:id])
  end

  def update
    @rant = Rant.find(params[:id])
    if @rant.user_id == current_user.id
      @rant.update(params.require(:rant).permit(:title, :body))
      redirect_to rants_path, notice: 'Rant was successfully edited.'
    else
      render :edit, notice: "Cannot edit this rant"
    end
  end

  def destroy
    @rant = Rant.find(params[:id])
    if @rant.user_id == current_user.id
      @rant.destroy
      redirect_to root_path, notice: "Rant was successfully destroyed."
    else
      render :edit, notice: "Cannot delete this rant"
    end
  end

  def owner_check
    @rant = current_user.rants.find_by(id: params[:id])
    if @rant.nil?
      redirect_to root_path, notice: "Who do you think you are?!"
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to rants_path, notice: 'Thanks for signing up for Rantly!'
    else
      render :new
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:first_name, :last_name, :email, :password))
      redirect_to user_path(@user), notice: 'User was successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

private
  def correct_user
    @rant = current_user.rants.find_by(id: params[:id])
    redirect_to root_path, notice: "not authorized to edit the rant" if @rant.nil?
  end

end

app/views/authentication/new.html.erb
authentication, new page



<%= form_tag @user do |f| %>

  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, class:"form-control" %>
  </div>


  <div class="form-group">
    <%= submit_tag "Sign in", class:"btn btn-primary" %>
  </div>

<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.present? %>
  <div class="alert alert-danger ">

    <strong>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this post from being saved:
    </strong>

      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:400,900|Laila:700|Hind:200'
      rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>

  <div class= "navbar">
    <div class="container">
      <%= link_to "Rantly", root_path  %>
        <span><%= link_to "Rants", root_path  %></span>
        <span><%= link_to "Users", users_path %></span>
        <% if !current_user %>
          <span><%= link_to "Sign Up", signup_path  %></span>
        <% end %>
        <% if current_user %>
          <span class = "pull-right"><%= current_user.full_name %></span>
        <% end %>
    </div>
  </div>

  <div class="header">
    <div class="container">

      <%= form_tag search_path, class:"search", :method => 'get' do %>
        <% if params['search'] == "" %>
          <%= text_field_tag :search, params[:search], placeholder: "This can't be blank!", class: "search" %>
        <% else %>
          <%= text_field_tag :search, params[:search], placeholder: "Search", class: "search" %>
        <!-- <%= submit_tag "Search", :name => nil, class: "btn btn-warning" %> -->
        <% end %>
      <% end %>

      <%= link_to "New Rant", new_rant_path, class: "new-button"  %>
    </div>
  </div>

<div class="container">
    <div class="profile-box">
      <% if current_user == nil %>
        <br>
        <%= form_tag signin_path do |f| %>

          <div class="has-feedback">
            <%= email_field_tag :email, nil, class:"user-form", placeholder: "Your email" %>
              <i class="fa fa-user form-control-feedback"></i>
          </div>
          <div class="has-feedback">
            <%= password_field_tag :password, nil, class:"user-form", placeholder: "Your password" %>
              <i class="fa fa-lock form-control-feedback"></i>
          </div>
            <%= submit_tag "Log In", class: "profile-button" %>
        <% end %>
      <% else %>
        <div class="profile-pic" style="background-image: url('<%= current_user.gravatar_url %>')">
        </div>
        <%= link_to "Log Out", signout_path, class: "profile-button drop"  %>
      <% end %>
      <%= yield :side_error %>
    </div>


      <div class="rcontainer">

    <% if notice.is_a? String %>
      <div class="text-center alert alert-info">
        <%= notice %>
      </div>
    <% end %>

      <span class="scroll"><%= yield %></span>

  </div>
</div>
  <script>
    $( ".delete-button" ).click(function() {
      $( ".rcontainer" ).fadeOut( 200 );
    });
  </script>

<!-- // <script>
  $( "delete-button" ).click(function() {
    $( ".rcontainer" ).fadeOut( "slow" );
  });
// </script> -->

</body>
</html>

app/views/rants/_form.html.erb
<div class="col-md-8">

  <% content_for :side_error do %>
    <br><%= render "layouts/errors", object: @rant %>
  <% end %>


  <div class="rant-box">
    <div class="rant-head">
      rant head

    <div class="avatar">
    </div>

  <div class="delete-button">
    <i class="fa fa-trash-o"></i>
    <%= link_to "D-stroy", rant_path(@rant), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>

<!-- # # # LOOKS GOOD BUT IS A DUMMY BUTTON # # #
    <div class="delete-button">
      <i class="fa fa-trash-o"></i> Delete
    </div> -->

    <div class="cancel-button">
    <i class="fa fa-sign-in"></i> Cancel
    </div>

    <div class="body-button">
      <i class="fa fa-upload"></i> Save
    </div>


      <h2>rant title</h2><br>
    </div>

this is janky.  fix it.

    <div class="rant-post">
        <%= form_for [@user, @rant] do |f| %>

          <div class="form-group">
            <%= f.label :title, class: "col-md-2" %>
            <%= f.text_field :title, class: "wide" %>
          </div>

          <div class="form-group">
            <%= f.label :body, class: "col-md-2" %>
            <%= f.text_area :body, class: "col-md-10" %>
          </div>


          <div class="form-group">
            <%= f.submit class:"btn btn-info col-md-offset-2" %>

          </div>

        <% end %>

    </div>

  </div>

</div>

app/views/rants/edit.html.erb
  <% content_for :side_error do %>
    <br><%= render "layouts/errors", object: @rant %>
  <% end %>

  <% if @rant.user == current_user %>
    <div class="rant-box">
      <%= form_for [@user, @rant] do |f| %>
          <div class = "rant-head">
              <h2><%= f.text_field :title, class: "wide" %></h2>
              <%= link_to " Delete", rant_path(@rant), method: :delete,
              class:"delete-button fa fa-trash-o" %>
              <%= link_to " Cancel", rants_path, class:"cancel-button fa fa-sign-in" %>

              <button class="body-button fa fa-upload lift"> Save</button>
          </div>

            <div class= "rant-post">
              <div class="avatar">
              </div>
                <%= f.text_area :body, class:"text-area message" %>
                <div class="count"></div>
            </div>
      <% end %>

    </div>
  <% end %>

app/views/rants/index.html.erb
<div class="scroll">

  <% if @rants.count > 0 %>
    <% @rants.reverse_each do |rant| %>
      <div class="rant-box">
        <div class="rant-head">

          <% if rant.user == current_user %>
            <%= link_to "Edit", edit_rant_path(rant), class: "body-button fa fa-edit" %>
          <% end %>

          <h2><%= link_to rant.title, rant_path(rant) %></h2><br>
        </div>

        <div class="avatar" style="background-image: url('<%= rant.user.gravatar_url %>')">
        </div>

        <div class="rant-post">
          <%= rant.body %>
        </div>

      </div>
    <% end %>

  <% else %>
    <div class="empty-result">
      <h2>These are not the droids you're looking for</h2>
    </div>
  <% end %>

</div>

app/views/rants/new.html.erb
<% content_for :side_error do %>
  <br><%= render "layouts/errors", object: @rant %>
<% end %>

  <div class="rant-box">
    <%= form_for [@user, @rant] do |f| %>
      <div class="rant-head">
        <%= link_to " Cancel", '#', class:"cancel-button fa fa-sign-in" %>
          <button class="body-button fa fa-upload lift"> Save</button>
        <h2><%= f.text_field :title, class: "wide", :placeholder => "Rant Title" %></h2>
      </div>

    <div class="rant-post">
      <div class="avatar">
      </div>
      <%= f.text_area :body, class:"text-area message", :placeholder => "Start your rant." %>
      <div class="count"></div>
      <% end %>
    </div>
  </div>

  </div>

</div>

app/views/rants/show.html.erb
<div class="scroll">

      <div class="rant-box">
        <div class="rant-head">

          <% if @rant.user == current_user %>
            <%= link_to "Edit", edit_rant_path(@rant), class: "body-button fa fa-edit" %>
          <% end %>

          <h2><%= @rant.title %></h2><br>
        </div>

        <div class="avatar">
        </div>

        <div class="rant-post">
          <%= @rant.body %>
        </div>

      </div>

</div>

app/views/users/_form.html.erb
<div class="scroll">
  <% content_for :side_error do %>
    <br><%= render "layouts/errors", object: @user %>
  <% end %>
  <div class="form">

    <%= form_for @user do |f| %>
      <%= f.text_field :first_name, class: "user-form", placeholder: "First Name" %>
      <%= f.text_field :last_name, class: "user-form", placeholder: "Last Name" %>
      <%= f.email_field :email, class: "user-form", placeholder: "Email" %>
      <div class="has-feedback lower-glyphicon">
        <%= f.password_field :password, class: "user-form", placeholder: "Password" %>
        <i class="fa fa-lock form-control-feedback"></i>
      </div>
      <%= f.submit "Log In", class:"profile-button" %>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h2>New User</h2>
</div>

<%= render 'form', title: "Edit" %>

app/views/users/index.html.erb
<div class="scroll">
  <div class="row">
    <% @users.reverse_each do |user| %>
      <div class="user-tile">
        <div class="avatar" style="background-image: url('<%= user.gravatar_url %>')">
          <!-- <%= image_tag user.gravatar_url %> -->
        </div>
        <div>
          <%= link_to user.full_name, user_path(user) %><br>
          <span><%= user.email %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form', title: "New" %>

app/views/users/show.html.erb
<div class="scroll">

<% @user.rants.reverse_each do |rant| %>
  <div class="rant-box">
    <div class="rant-head">

      <% if rant.user == current_user %>
        <%= link_to "Edit", edit_rant_path(rant), class: "body-button fa fa-edit" %>
      <% end %>

      <h2><%= link_to rant.title, rant_path(rant) %></h2><br>
    </div>

        <div class="avatar" style="background-image: url('<%= rant.user.gravatar_url %>')">
    </div>

    <div class="rant-post">
      <%= rant.body %>
    </div>

  </div>
<% end %>
</div>